### ISSUE TITLE
Create/Send Transactions From BIP49/BIP84 

### ISSUE THREAD

**Issue by Droppix** [BTCGPU/bitcoinjs-lib#14]
Hi,

I try to create & send transaction (Testnet) with bgoldjs-lib, but I have some issues on ;

BIP44 to BIP44 : Create & Send : OK
BIP44 to BIP49 : Create & Send : OK
BIP44 to BIP84 : Create & Send : OK

**BIP49 to BIP44 : Create OK, but Send error :** '-26: non-mandatory-script-verify-flag (Signature hash type missing or not understood) (code 64)'

```
let privateKey = ...
 const ecpair = bgoldjs.ECPair.fromWIF(privateKey, this.network)
 let pubKeyHash = bgoldjs.crypto.hash160(ecpair.getPublicKeyBuffer())

let redeemScript = bgoldjs.script.witnessPubKeyHash.output.encode(pubKeyHash)
let redeemScriptHash = bgoldjs.crypto.hash160(redeemScript)
let scriptPubKey = bgoldjs.script.scriptHash.output.encode(redeemScriptHash)

txb.addInput(input.txid, input.vout, bgoldjs.Transaction.DEFAULT_SEQUENCE)

txb.sign(0, ecpair, redeemScript, null, input.value)
let rawTx = txb.build().toHex()   
...

```
**BIP84 to BIP44 : Create OK, but Send error :** '-26: non-mandatory-script-verify-flag (Witness requires empty scriptSig) (code 64)'

```
let privateKey = ...
 const ecpair = bgoldjs.ECPair.fromWIF(privateKey, this.network)
 let pubKeyHash = bgoldjs.crypto.hash160(ecpair.getPublicKeyBuffer())
let scriptPubKey = bgoldjs.script.pubKeyHash.output.encode(pubKeyHash)                         
txb.addInput(input.txid, input.vout, bgoldjs.Transaction.DEFAULT_SEQUENCE, scriptPubKey)

let hashTypes = bgoldjs.Transaction.SIGHASH_ALL | bgoldjs.Transaction.SIGHASH_FORKID
txb.sign(index, ecpair, undefined, hashTypes, input.value)
let rawTx = txb.build().toHex()   
...

```

Any suggestions ?

Thanks

**Comment by h4x3rotab** [comment]
It looks like the problem is about signing native & legacy segwit transactions. I'd love to debug it. It will be helpful if you can provide a code snippet for the problem reproduce. I guess it could be a mistake in the testnet configuration.

Btw, we are on a big upgrade of bgoldjs-lib. We are going to follow the the upstream at the latest version.

**Comment by Droppix** [comment]
Thanks for you response...but I found 2 problems (forget hashTypes on txb.sign + scriptPubKey on txb.addInput...)
Everything seems to work!
