### ISSUE TITLE
Handle prefork hash correctly

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/bitcoinjs-lib#3]
```js
block100.getHash().reverse().toString('hex');
```
It produces the wrong hash for block 100: `7644500d651d8db203d8dfdb7053da2cffe8dffcb9a1bc115da63e047dfb7c17`

The reason is that it tries to serialize a prefork Bitcoin block in the BTG block header manner. It will produce wrong hash and thus can't pass the target check as well.

Note that explorer.bitcoingold.org also has the same problem (so don't see it as the ground truth).

Solution: check the block height before doing serialization just like [how BTG Core handles it](https://github.com/BTCGPU/BTCGPU/blob/530ed7c79fa7b5affd7a952ba42779d5bf58b5fc/src/primitives/block.h#L54).

Test vector: [block 100](https://explorer.bitcoingold.org/insight-api/rawblock/000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a)
Hash: `000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a`
Height: `100`
Hex: 
```
0100000095194b8567fe2e8bbda931afd01a7acd399b9325cb54683e64129bcd00000000660802c98f18fd34fd16d61c63cf447568370124ac5f3be626c2e1c3c9f0052d000000000000000000000000000000000000000000000000000000000000000019a76949ffff001d33f3c25d00000000000000000000000000000000000000000000000000000000000101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0704ffff001d014dffffffff0100f2052a01000000434104e70a02f5af48a1989bf630d92523c9d14c45c75f7d1b998e962bff6ff9995fc5bdb44f1793b37495d80324acba7c8f537caaf8432b8d47987313060cc82d8a93ac00000000
```

**Comment by Vutov** [comment]
https://github.com/BTCGPU/bitcoinjs-lib/pull/5
