### ISSUE TITLE
Move btgForkHeight to network parameter

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/bitcoinjs-lib#4]
https://github.com/BTCGPU/bitcoinjs-lib/blob/c92fa78674a59ac9dd67e8b0ee6a0ec85e91d569/src/block_gold.js#L23

`btgForkHeight` varies in different network (mainnet, testnet, regtest, etc). So it's not wise to hardcode it here.

**Comment by Vutov** [comment]
https://github.com/BTCGPU/bitcoinjs-lib/pull/5

**Comment by h4x3rotab** [comment]
Nice
